トップ画面を作成しました。Web版とモバイル版の調整をScssで行いました。
yousukeend/alpinea pull request #20
Opened 2023-06-04 12:14 UTC by yousukeend

## Checklist for Developer

- [x] 最新のdevelopブランチをPullした。 Pulled the latest develop branch.
- [x] Pull RequestをIssueに紐付けた。 Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## そのほかの関連するIssue / Related issues other than connected one
- #2 
## 変更内容 / Details of Changes
トップ画面の作成をしました。
Web版とモバイル版でScssを使って調整しました。
## スクリーンショット / Screenshots

![スクリーンショット 2023-06-04 21 10 44](https://github.com/yousukeend/alpinea/assets/40225496/ff3c5b70-4842-451c-b373-187c67068c6e)

モバイル版では「はじめる」ボタンが少し横に長くなる
## レビューするポイント/ Points for review

- localhost:4200にアクセスしてトップページが作成されていること。
- 画面の幅が小さくなると、「はじめる」ボタンが少し横に長くなっていること

2023-06-06 03:05 UTC, k-hayashi-dott requested changes

2023-06-06 03:05 UTC, k-hayashi-dott commented on angular-app/package.json
>      "@angular/router": "^16.0.0",
16.0.2 にバージョン合わせたほうが良いかなーと思いました〜

2023-06-09 05:38 UTC, yousukeend commented
@k-hayashi-dott 
バージョンを統一しました。
よろしくお願いします！

2023-06-09 05:38 UTC, k-hayashi-dott approved these changes
あざす！

2023-06-09 05:38 UTC, merged