Lodashをインストールし、問題を7問ランダムに取得する変更を加えました。
yousukeend/alpinea pull request #34
Opened 2023-07-25 07:14 UTC by yousukeend

再スタートでランダムに問題が出題されるように変更しました。

2023-07-31 06:06 UTC, yousukeend commented
## Checklist for Developer

- [x] 最新のdevelopブランチをPullした。 Pulled the latest develop branch.
- [x] Pull RequestをIssueに紐付けた。 Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## そのほかの関連するIssue / Related issues other than connected one

- #13 

## 変更内容 / Details of Changes
1. quizサービスでランダムな問題を管理し、judgementサービスで正誤判定を管理するように分けました。
2. 出題問題の選択肢でランダムに表示するように変更しました。

## スクリーンショット / Screenshots

![スクリーンショット 2023-07-31 15 03 46](https://github.com/yousukeend/alpinea/assets/40225496/1046c93b-d4ff-40a0-b2fc-9fed6736776f)


- こちらが`localhost:4200/quiz`クイズ画面。
- 選択肢がランダムに表示されるように変更。


## レビューするポイント/ Points for review
- `localhost:4200/quiz`クイズ画面で選択肢がランダムに表示されること。

2023-07-31 07:40 UTC, k-hayashi-dott commented on angular-app/src/app/quiz-page/quiz-page.component.html
> +      (click)="onClickAnswer(ansOption)"
デグレしてます。

2023-07-31 07:40 UTC, k-hayashi-dott commented on angular-app/src/app/quiz-page/quiz-page.component.ts
> +    );
同じくデグレ

2023-07-31 07:59 UTC, k-hayashi-dott commented
- pages/ページ名/各ファイル
- services/service.ts
階層化しましょう。インターンアプリを思い出してください。

2023-07-31 08:07 UTC, k-hayashi-dott requested changes
一見、動作しているように見えますが、
Quiz / Judgement page component で毎回QuizService を初期化しているので、
選択した回答と、正誤判定がおかしくなっています。
console.log を出しながら、問題１〜問題７まで同じService を使っているか？確認してみましょう。

RxJS / Service / 状態管理 というキーワードで調査してみてください。

2023-07-31 08:07 UTC, k-hayashi-dott commented on angular-app/src/app/quiz-page/quiz-page.component.html
page であることは自明なので
quiz という名称で。
別コメントしているように page ファイルは page ディレクトリ下にまとめてくだしあ。

2023-08-01 08:57 UTC, k-hayashi-dott commented on angular-app/src/app/quiz-page/quiz-page.component.ts
> +  randomQuizList: string[] = [];
ごめんなさい、このLISTの役割は選択肢なんですね。
QuizList なので、出題クイズの配列を持っているのかと思いました。
なので適切な命名にしてください。
Choise 等を使って。

2023-08-07 07:47 UTC, yousukeend commented
画面の見た目は変わりありませんが、
以前、ページ遷移(`/quiz` から`/judge`)するときに毎回問題をランダムに出題されていました。

これを今回は、問題が始まる`/info`で`quizService.tsのstartQuiz()`を呼び出すことで解決しました。

また以前、`/quiz`と`/judge`のそれぞれテンプレート側で直接サービスを呼び出していました。
これを今回は、コンポーネント側で処理をさせてテンプレート側で直接サービスを呼び出さないように工夫しました。

2023-08-08 04:26 UTC, k-hayashi-dott commented on angular-app/src/app/pages/quiz/quiz.component.html
>      >
選択肢の順番もランダムで並び替えしているので、正誤判定がおかしくなっていますね。
randomChoice の 0番目が必ず正解になっているわけではないかと思います。

2023-08-08 04:27 UTC, k-hayashi-dott commented on angular-app/src/app/pages/quiz/quiz.component.ts
> +    );
選択肢だけの配列ではなくて、元々の配列番号と選択肢を持つ2次元配列か、Object の配列にする必要があります。

2023-08-08 04:28 UTC, k-hayashi-dott commented on angular-app/src/app/pages/result/result.component.ts
> +  }
restart した後、もう1度クイズを実行しようと思うと、問題が出題されません。

2023-08-08 04:30 UTC, k-hayashi-dott commented on angular-app/src/app/pages/result/result.component.ts
> +  }
また、init という役割は処理の最初に行うべきなので、ここで init を実行せず、クイズの最初のページで init を行うべきです。

2023-08-08 04:35 UTC, k-hayashi-dott commented on angular-app/src/app/services/quiz.service.ts
> +  }
init する内容はこれだけでよいでしょうか？
restart した際に、なんの値が、何に影響してエラーになっているかを特定して、init する内容を見直してみましょう。

2023-08-08 04:36 UTC, k-hayashi-dott commented on angular-app/src/app/services/judgement.service.ts
> +  }
Quiz Service に持っているものと役割がかぶるのでこっちはいらないじゃないでしょうか。

2023-08-08 04:37 UTC, k-hayashi-dott requested changes
- 選択肢がランダムになっているので、単純に配列0番目判定では正誤判定できない
- restart したときの各カウンターがおかしいため2回目の実行が失敗する
@yousukeend 確認お願いします！

2023-08-08 04:58 UTC, k-hayashi-dott commented on angular-app/src/app/pages/info/info.component.html
> +    (click)="this.quizService.startQuiz()"
ここでまだ component から直接 Service を実行しちゃってますね。

2023-08-08 04:59 UTC, k-hayashi-dott reviewed
コメント追記

2023-08-08 08:06 UTC, abe127 commented
1. const.tsのクイズデータを修正する
2. restartした時にエラーが発生するか確認し、スクショか動画をコメントする
3. 2のエラーを修正する
4. quizCountの件を修正する
  5. https://github.com/yousukeend/alpinea/pull/34#discussion_r1286585175

2023-08-09 01:47 UTC, yousukeend commented
@k-hayashi-dott 
リスタートさせた時、
第二問目でデータが表示されないことをこちらでも確認したので後ほど修正します！

## リスタートした時、第二問目でエラーが確認された
<img width="1381" alt="スクリーンショット 2023-08-09 10 27 19" src="https://github.com/yousukeend/alpinea/assets/40225496/fa5b62ee-3736-4116-a673-55d99f79e1bc">

- リスタートさせた時、第二問目でエラーを確認できた。

## クイズをもう一度プレイする時の動作状況

![alpinea_test01](https://github.com/yousukeend/alpinea/assets/40225496/eac46d18-d6ed-4258-bdf3-3779b7d5c2ac)

- リスタートさせた時の動作状況で、第二問目でエラーを確認できた。

2023-08-10 01:47 UTC, yousukeend commented
@k-hayashi-dott 
こちらコメントを元に修正しました。お時間ある際、よろしくお願いします！

- リスタートさせた時でも、動作できるように変更しました。
- クイズデータを初期化するタイミングを変更しました。
- 正誤判定をランダムな選択肢であっても、正しく動作するように変更しました。
- クイズ元の選択肢をstring型からオブジェクト型へ変更しました。

2023-08-10 04:01 UTC, k-hayashi-dott commented on angular-app/src/app/services/judgement.service.ts
> +  quizCount: number = 1;
いまいち意図を伝えきれずすいません。

これを削除したいです。QuizService の randomQuizCount を使えば良いので。
ずっと言っている通り、この Service は正誤判定をする Service なのでクイズの進行管理をする Service ではないです。

2023-08-10 04:01 UTC, k-hayashi-dott commented on angular-app/src/app/services/judgement.service.ts
> +  nextQuiz() {
nextQuiz は QuizService へ移動する。

2023-08-10 04:19 UTC, k-hayashi-dott commented on angular-app/src/app/services/judgement.service.ts
> +  }
quizservice へ移動

2023-08-10 04:20 UTC, k-hayashi-dott commented on angular-app/src/app/pages/quiz/quiz.component.ts
> +    this.quizCount = this.judgementService.getQuizCount();
quiz service から取得するようにする

2023-08-10 04:21 UTC, k-hayashi-dott requested changes
@yousukeend 
動作はOKです！
Service の役割の分離がもうひとつ必要ですよろしくお願いします！

2023-08-10 04:26 UTC, k-hayashi-dott commented on angular-app/src/app/pages/quiz/quiz.component.ts
> +    );
currentQuizText は getter を使えているのに、
quizImg は直接アクセスしてしまっていますね。
currentQuizText に合わせましょう

2023-08-10 04:28 UTC, k-hayashi-dott commented on angular-app/src/app/services/quiz.service.ts
> +  quizList = QUIZ_LIST;
すべてprivate にしましょう。役割によって private / public を切り替えればよいのですが、
カプセル化をして、各component から直接アクセスするようにしない記述を身につけましょう。

2023-08-10 04:28 UTC, k-hayashi-dott commented on angular-app/src/app/services/judgement.service.ts
> +  isCorrectAnswer: boolean = false;
private にしましょう

2023-08-10 04:29 UTC, k-hayashi-dott requested changes
カプセル化しましょー

2023-08-12 06:44 UTC, yousukeend commented
@k-hayashi-dott cc: @hikaru-nakamura-thedott 
カプセル化にするよう変更しました。
よろしくお願いします！

2023-08-14 01:18 UTC, k-hayashi-dott approved these changes
ありがとうございましたー

2023-08-14 02:58 UTC, merged