総合結果画面で正しく正解数と階級が表示されるように変更しました。
yousukeend/alpinea pull request #35
Opened 2023-08-14 06:01 UTC by yousukeend

## Checklist for Developer

- [x] 最新のdevelopブランチをPullした。 Pulled the latest develop branch.
- [x] Pull RequestをIssueに紐付けた。 Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## そのほかの関連するIssue / Related issues other than connected one

- #15 

## 変更内容 / Details of Changes
1. 総合結果画面で正解数と階級が正しく表示されるように変更しました。

## スクリーンショット / Screenshots
### 全問正解(7問)で「プロ」の階級表示

![スクリーンショット 2023-08-14 14 44 55](https://github.com/yousukeend/alpinea/assets/40225496/c62b851f-9722-43d0-8ca4-f89b5dc54ecf)

- 7問正解と表示される。
- 全て正解したので「プロ」という階級が表示される。

### 5~6問正解で「上級者」の階級表示

![スクリーンショット 2023-08-14 14 45 48](https://github.com/yousukeend/alpinea/assets/40225496/b79755ff-b7a0-43a2-a716-967f90fe909c)

- 5~6問正解すると、「上級者」という階級が表示される。

### 3~4問正解で「中級者」の階級表示

![スクリーンショット 2023-08-14 14 44 01](https://github.com/yousukeend/alpinea/assets/40225496/a021e484-5ade-4eae-975a-93d75ba6f3c2)

- 3~4問正解すると、「中級者」という階級が表示される。

### 0~2問正解で「初心者」の階級表示

![スクリーンショット 2023-08-14 14 46 27](https://github.com/yousukeend/alpinea/assets/40225496/be97cc0d-d64f-4f8b-b108-16a6bb4109f3)

- 0~2問正解すると、「初心者」という階級が表示される。

## レビューするポイント/ Points for review
- `localhost:4200/result`総合結果画面で、上記のスクショのように正しく正解数と階級が表示される

2023-08-15 07:07 UTC, hikaru-nakamura-thedott requested changes

2023-08-15 07:07 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/result/result.component.ts
> +  }
以下で良いかと思いました。

```javascript
    if (score === 7) {
      this.userSkillLevel = 'プロ';
    } else if (score >= 5) {
      this.userSkillLevel = '上級者';
    } else if (score >= 3) {
      this.userSkillLevel = '中級者';
    } else {
      this.userSkillLevel = '初心者';
    }
```

2023-08-15 07:43 UTC, hikaru-nakamura-thedott requested changes

2023-08-15 07:43 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/services/judgement.service.ts
>    setJudgeAns(ans: boolean) {
変数名が曖昧で実際の用途と命名がすれ違っているような気がします。

2023-08-18 04:23 UTC, yousukeend commented
@hikaru-nakamura-thedott 
再度レビューお願いします！

2023-08-22 07:05 UTC, k-hayashi-dott commented on angular-app/src/app/pages/result/result.component.ts
> +    if (score >= 7) {
以上　になることあるでしょうか？

2023-08-28 03:50 UTC, k-hayashi-dott approved these changes
ありがとうございます〜

2023-08-28 05:17 UTC, k-hayashi-dott reviewed
戻さなくても別に良かったですが、、、
別Issueで対応されるとのことなので、承知しました。
なお、元々してあった対応がマジックナンバー対応であったら不完全です。
このファイル意外にも「7」という数字は登場しているかと思います。

2023-08-29 06:45 UTC, hikaru-nakamura-thedott requested changes
`classifySkillLevel()` をServiceに置いた理由は「汎用的に使えるようにするため」だったと思います。
あちこちから汎用的に呼び出す際に今の実装だと、以下の手順を産まなければいけません。
1. JudgementServiceのquizScoreにスコアを格納
2. classifySkillLevel()を実行
3. JudgementServiceのquizScoreを取得

JudgementServiceに格納してあるquizScoreじゃないと判断できないため、冗長かつ密結合になる。

2023-08-29 06:45 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/services/judgement.service.ts
> +    }
classifySkillLevel()はnumber型のスコア(score)を受け取って、"プロ"や"初心者"という文字列を返すメソッドにしてください。

2023-08-29 06:45 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/result/result.component.ts
> +    this.userSkillLevel = this.judgementService.userSkill;
classifySkillLevel()はnumber型のスコア(score)を受け取って、"プロ"や"初心者"という文字列を返すメソッドにしてください。
classifySkillLevel()の戻り値を `this.userSkillLevel` に格納してください。

2023-08-29 06:45 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/services/judgement.service.ts
> +  get userSkill(): string {
「ユーザースキル」（`userSkill()`）が「レベル」（`_userSkillLevel`）を返すのはおかしいと思います。
適切な変数名にしてください。

2023-08-29 08:42 UTC, yousukeend commented
@k-hayashi-dott @hikaru-nakamura-thedott 
こちら修正しました。よろしくお願いします！

2023-08-29 08:57 UTC, hikaru-nakamura-thedott requested changes

2023-08-29 08:57 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/result/result.component.ts
> +      this.quizScore
せっかく `userSkillLevel()` を定義しているなら、ここで使えばいいかなと思いました〜。
`userSkillLevel()` をここで使わないなら、 `userSkillLevel()` は他に使われていないので、削除でも良いかと。
もし、他で使うという展望などあれば教えてください。

2023-08-31 02:32 UTC, yousukeend commented
@hikaru-nakamura-thedott 
`userSkillLevel()` を使うように修正しましたので、よろしくお願いします！

2023-09-05 06:29 UTC, merged