外部のjsonファイルにクイズデータを持たせて、クイズアプリに反映させるように変更しました。
yousukeend/alpinea pull request #43
Opened 2023-09-04 04:24 UTC by yousukeend

## Checklist for Developer

- [x] 最新のdevelopブランチをPullした。 Pulled the latest develop branch.
- [x] Pull RequestをIssueに紐付けた。 Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## そのほかの関連するIssue / Related issues other than connected one

- #39 

## 変更内容 / Details of Changes
1. 外部にJSONファイルを作成し、クイズアプリで反映されるように変更しました。

## スクリーンショット / Screenshots

## レビューするポイント/ Points for review
- クイズアプリでクイズデータが正しく表示されること。

2023-09-04 05:22 UTC, k-hayashi-dott approved these changes

2023-09-04 05:30 UTC, k-hayashi-dott requested changes

2023-09-04 05:30 UTC, k-hayashi-dott commented on angular-app/src/app/services/quiz.service.ts
> +    this.http.get('../assets/const.json').subscribe((quizData: any) => {
このファイルがコミットされてないですねー

2023-09-04 05:31 UTC, k-hayashi-dott commented on angular-app/src/app/services/quiz.service.ts
> +    this.http.get('../assets/const.json').subscribe((quizData: any) => {
それと、最新のDevelopではないようです。

2023-09-05 06:31 UTC, k-hayashi-dott commented on angular-app/src/app/services/quiz.service.ts
> +    this.http.get('../assets/const.json').subscribe((quizData: any) => {
@yousukeend 
遅くなりましたが前のPRをマージしたので、コンフリクト解消（develop から作業し直したほうが早いかも）お願いします！

2023-09-05 07:19 UTC, k-hayashi-dott commented on angular-app/src/app/services/quiz.service.ts
> +    this.http.get('../assets/const.json').subscribe((quizData: any) => {
> 外部のJSONファルを置く場所はどこに配置するのがベストなのか質問したいです。app/assets/const.json
ファイルの場所はOKですが、ファイル名に気をを使ってほしいのと、コメントに残してる通りファイルがコミットされてないのです！

2023-09-05 07:50 UTC, k-hayashi-dott requested changes
@yousukeend 
型指定をお願いしますー

2023-09-05 07:50 UTC, k-hayashi-dott commented on angular-app/src/app/services/quiz.service.ts
> +    });
any を使わずに型を指定してみましょう。
https://angular.jp/tutorial/tour-of-heroes/toh-pt6

2023-09-05 08:14 UTC, yousukeend commented
@k-hayashi-dott 
型指定を変更しました！よろしくお願いします！

2023-09-05 08:28 UTC, k-hayashi-dott approved these changes
OKです！

2023-09-05 08:28 UTC, merged